# -*- mode: ruby -*-
# vi: set ft=ruby :
IMAGE_ubuntu_2204   = "bento/ubuntu-22.04"
## Vagrant will not perform any parallel operations (such as parallel box provisioning)
ENV['VAGRANT_NO_PARALLEL'] = 'no'
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  # config.vm.provision "shell", path: "bootstrap.sh"
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  NumberOfNodeType1 = 1
  (1..NumberOfNodeType1).each do |type1_id|
    config.vm.define "ansibleHost#{type1_id}" do |type1_vm|
      type1_vm.vm.box = IMAGE_ubuntu_2204
      type1_vm.vm.hostname = "ansibleHost#{type1_id}.ansible.com"
      type1_vm.vm.network "private_network", ip: "192.168.56.10#{type1_id}"
      type1_vm.vm.provider "virtualbox" do |v|
        v.name = "type1#{type1_id}"
        v.memory = 1024
        v.cpus = 1
      end
      type1_vm.vm.provision "shell", path: "bootstrap_host.sh"
    end
  end

  NumberOfNodeType2 = 2
  (1..NumberOfNodeType2).each do |type2_id|
    config.vm.define "ansibleClient#{type2_id}" do |type2_vm|
      type2_vm.vm.box = IMAGE_ubuntu_2204
      type2_vm.vm.hostname = "ansibleClient#{type2_id}.ansible.com"
      type2_vm.vm.network "private_network", ip: "192.168.56.11#{type2_id}"
      type2_vm.vm.provider "virtualbox" do |v|
        v.name = "type2#{type2_id}"
        v.memory = 1024
        v.cpus = 1
      end
      type2_vm.vm.provision "shell", path: "bootstrap_client.sh"
    end
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
