IMAGE_ubuntu_2204   = "bento/ubuntu-22.04"
IMAGE_Debian_12     = "bento/debian-12"

Vagrant.configure("2") do |config|
  config.vm.box = IMAGE_ubuntu_2204
  config.vm.hostname = "TestLab"
  config.vm.network "private_network" , ip: "192.168.56.150"
  config.vm.provider "virtualbox" do |myVM|
    myVM.name = "TestLab"
    myVM.memory = 1024
    myVM.cpus = 1
  end
  config.vm.provision :shell, path: "bootstrap.sh"
end