FROM ubuntu:20.04

LABEL maintainers=parsa
ENV DEBIAN_FRONTEND=noninteractive


RUN sleep 20 && apt update && \
    apt install -y --no-install-recommends --no-install-suggests\
    nginx
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log 

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]